#!/bin/bash
#
# Copyright (C) 2016 Cihangir Akturk <cihangir.akturk@tubitak.gov.tr>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# mkefi
__ScriptVersion="0.0.2"
if [ -n "$DEBUG" ]; then
    set -x
fi

MENTRY_DEFAULT="Start Pardus Kurumsal"
MENTRYSAFE_DEFAULT="Start Pardus Kurumsal in basic graphics mode"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage()
{
    echo "Usage : $0 [-h] [-v] --cdlabel LABEL --input LEGACY_ISO --output EFI_ISO
                     [-m TITLE] [-s TITLE]

    mandatory arguments:
     -l, --cdlabel       set volume name to cdlabel
     -i, --input         path to legacy ISO file
     -o, --output        put new UEFI ISO into this file

    optional arguments
     -m, --mentry        set default grub menuentry title
     -s, --mentrysafe    set safe-mode grub menuentry title
     -h, --help          display this message and exit
     -v, --version       display script version"

}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------
NUM_ARGS=$#

# Transform long options to short ones
for arg in "$@"; do
    shift
    case "$arg" in
        "--help") set -- "$@" "-h" ;;
        "--version") set -- "$@" "-v" ;;
        "--cdlabel") set -- "$@" "-l" ;;
        "--input") set -- "$@" "-i" ;;
        "--output") set -- "$@" "-o" ;;
        "--mentry") set -- "$@" "-m" ;;
        "--mentrysafe") set -- "$@" "-s" ;;
        *) set -- "$@" "$arg"
    esac
done

while getopts ":l:i:o:m:s:hv" opt; do
    case $opt in
        h|help)
            usage; exit 0
            ;;
        v|version)
            echo "$0 -- Version $__ScriptVersion"; exit 0
            ;;
        l|cdlabel)
            ARG_CDLABEL=$OPTARG
            ;;
        i|input)
            ARG_INPUT=$OPTARG
            ;;
        o|output)
            ARG_OUTPUT=$OPTARG
            ;;
        m|mentry)
            ARG_MENTRY=$OPTARG
            ;;
        s|mentrysafe)
            ARG_MENTRYSAFE=$OPTARG
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        *)
            >&2 echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac    # --- end of case ---
done
shift $(($OPTIND-1))

NUM_REQIRED_ARGS=6
if [[ "$NUM_ARGS" -lt "$NUM_REQIRED_ARGS" ]]; then
    >&2 usage
    exit 1
fi

function die_err()
{
    >&2 echo "$1"
    exit 1
}

if [[ -z "$ARG_CDLABEL" ]] || [[ -z "$ARG_INPUT" ]] || \
   [[ -z "$ARG_OUTPUT" ]] ; then
   usage; exit 1
fi

if [[ -z "$ARG_MENTRY" ]] ; then
    ARG_MENTRY=$MENTRY_DEFAULT
fi
if [[ -z "$ARG_MENTRYSAFE" ]] ; then
    ARG_MENTRYSAFE=$MENTRYSAFE_DEFAULT
fi

#===  FUNCTION  ================================================================
#         NAME:  do_mkimage
#  DESCRIPTION:  make EFI bootable grub binary
#  ARGUMENTS  : $1 - arch (x86, x86_64)
#               $2 - directory where grub modules reside in
#               $3 - write the generated file to $1
#  example: do_mkimage x86_64-efi /usr/lib/grub/x86_64-efi/ ./bootx64.efi
#===============================================================================
function do_mkimage()
{
    ERR=$(grub-mkimage -d $2 -o $3 \
        -O $1 -p "/EFI/BOOT" all_video boot btrfs cat chain configfile \
        echo efifwsetup  efinet ext2 fat font gfxmenu gfxterm gzio halt \
        hfsplus iso9660  jpeg loadenv lvm mdraid09 mdraid1x minicmd normal \
        part_apple part_msdos part_gpt password_pbkdf2 png reboot search \
        search_fs_uuid search_fs_file search_label sleep syslinuxcfg test \
        tftp regexp video xfs linux 2>&1)

    if [[ $? != 0 ]]; then
        echo "grub-mkimage: failed to create boot image:" $ERR
        exit 127;
    fi
    return 0
}

#===  FUNCTION  ================================================================
#         NAME:  gen_grub_cfg
#  DESCRIPTION:  generate grub.cfg
#  ARGUMENTS  :  $1 - CDLABEL
#  ARGUMENTS  :  $2 - /path/to/grub.cfg
#===============================================================================
function gen_grub_cfg()
{
    cat << EOF > $2
set default="0"

function load_video {
  insmod efi_gop
  insmod efi_uga
  insmod video_bochs
  insmod video_cirrus
  insmod all_video
}

load_video
set gfxpayload=keep
insmod gzio
insmod part_gpt
insmod ext2

set timeout=10
### END /etc/grub.d/00_header ###

search --no-floppy --set=root -l '${1}'

### BEGIN /etc/grub.d/10_linux ###
menuentry '${ARG_MENTRY}' --class pardus --class gnu-linux --class gnu --class os {
	linux /live/vmlinuz root=/dev/disk/by-label/${1} boot=live config live-config.username=pardus live-config.user-fullname=pardus live-config.hostname=pardus live-config.timezone=Europe/Istanbul live-config.utc=yes live-config.nottyautologin live-config.locales=tr_TR.UTF-8,en_US.UTF-8 locale=tr_TR keyboard-layouts=tr keyboard-model=pc105 modprobe.blacklist=floppy file=/cdrom/install/preseed.cfg splash quiet --
	initrd /live/initrd.img
}
menuentry '${ARG_MENTRYSAFE}' --class pardus --class gnu-linux --class gnu --class os {
	linuxefi /live/vmlinuz root=/dev/disk/by-label/${1} boot=live config live-config.username=pardus live-config.user-fullname=pardus live-config.hostname=pardus live-config.timezone=Europe/Istanbul live-config.utc=yes live-config.nottyautologin live-config.locales=tr_TR.UTF-8,en_US.UTF-8 locale=tr_TR keyboard-layouts=tr keyboard-model=pc105 modprobe.blacklist=floppy file=/cdrom/install/preseed.cfg splash quiet --
	initrdefi /live/initrd.img
}
EOF
    if [[ $? != 0 ]]; then
        echo "Could not generate grub.cfg exiting"
        exit 127;
    fi
}

#===  FUNCTION  ================================================================
#         NAME:  create_efiboot_img
#  DESCRIPTION:  create pseude filesystem image
#  ARGUMENTS  : $1 - path/to/efiboot.img
#===============================================================================
function create_efiboot_img()
{
    OUT=$(dd if=/dev/zero of=$1 bs=1M count=4 2>&1)

    if [[ $? != 0 ]]; then
        echo "dd: failed to create:" $1
        exit 127;
    fi

    OUT=$(mkfs.vfat -F12 -n "EFI" $1 2>&1)
    if [[ $? != 0 ]]; then
        echo "mkfs.vfat error:" $OUT
        exit 127;
    fi

    return 0
}

function mktmpdir()
{
    ARGS=""
    if [[ -n $1 ]]; then
        ARGS="--tmpdir=${1}"
    fi

    TMPDIR=$(mktemp ${ARGS} -d 2>&1)

    if [[ $? != 0 ]]; then
        echo "mktemp error" $TMPDIR
        exit 127;
    fi

    echo ${TMPDIR}
}

function mktmpfile()
{
    ARGS=""
    if [[ -n $1 ]]; then
        ARGS="--tmpdir=${1}"
    fi

    TMPDIR=$(mktemp ${ARGS} 2>&1)

    if [[ $? != 0 ]]; then
        echo "mktemp error" $TMPDIR
        exit 127;
    fi

    echo ${TMPDIR}
}

#===  FUNCTION  ================================================================
#         NAME:  cp_a
#  DESCRIPTION:  cp src to dst while preserving mode, ownership. timestamps
#  ARGUMENTS  :  $1 - src
#  ARGUMENTS  :  $2 - dst
#===============================================================================
function cp_a()
{
    local src=$1
    local dst=$2

    ERR=$(cp -a ${src} ${dst} 2>&1)

    if [[ $? != 0 ]]; then
        echo "${ERR}"
        exit 127;
    fi
}
function cp_f()
{
    local src=$1
    local dst=$2

    ERR=$(cp -f ${src} ${dst} 2>&1)

    if [[ $? != 0 ]]; then
        echo "${ERR}"
        exit 127;
    fi
}

#===  FUNCTION  ================================================================
#         NAME:  populate_efiboot_img
#  DESCRIPTION:  populate EFI dirs and copy grub bootloader into this fs
#  ARGUMENTS  :  $1 - CDLABEL - volume label
#  ARGUMENTS  :  $2 - path/to/directory
#===============================================================================
function populate_efiboot_img()
{
    TMPMNT=$(mktmpdir /tmp)
    create_efiboot_img ${2}/efiboot.img
    mount_fs ${2}/efiboot.img ${TMPMNT}

    if ! mkdir -p ${TMPMNT}/EFI/BOOT > /dev/null 2>&1 ; then
        echo "mkdir error"
        exit 127;
    fi

    do_mkimage x86_64-efi /usr/lib/grub/x86_64-efi/ ${TMPMNT}/EFI/BOOT/BOOTX64.EFI
    gen_grub_cfg ${1} ${TMPMNT}/EFI/BOOT/grub.cfg
    umount_fs ${TMPMNT}
    rm -fr ${TMPMNT} > /dev/null 2>&1
}

#===  FUNCTION  ================================================================
#         NAME:  gen_iso_image
#  DESCRIPTION:  generate UEFI ISO image
#  ARGUMENTS  :  $1 - place output ISO image in $1
#  ARGUMENTS  :  $2 - volume id
#  ARGUMENTS  :  $3 - /path/to/syslinux/installation/on/your/system
#  ARGUMENTS  :  $4 - /path/to/legacy/rootfs
#===============================================================================
function gen_iso_image()
{
    ISOFILEPATH=$1
    VOLID=$2
    SYSLINUXPATH=$3
    ROOTFS=$4

    echo "Generating ISO: ${ISOFILEPATH}"
    ERR=$(xorriso -as mkisofs -o ${ISOFILEPATH} -volid ${VOLID} \
        -isohybrid-mbr ${SYSLINUXPATH}/isohdpfx.bin -c isolinux/boot.cat -b \
        isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
        -eltorito-alt-boot -e isolinux/efiboot.img -no-emul-boot \
        -isohybrid-gpt-basdat ${ROOTFS} 2>&1)

    if [[ $? != 0 ]]; then
        echo "${ERR}";
        exit 127;
    fi
}

#===  FUNCTION  ================================================================
#         NAME:  mount_fs
#  DESCRIPTION:  mount filesystem image
#  ARGUMENTS  :  $1 - path/to/fs.img
#                $2 - path/to/mountpoint
#===============================================================================
function mount_fs()
{
    if ! mount $1 $2 > /dev/null 2>&1 ; then
        echo "Failed to mount" $1
        exit 127;
    fi
    return 0
}

#===  FUNCTION  ================================================================
#         NAME:  umount_fs
#  DESCRIPTION:  umount filesystem mounted at $1
#  ARGUMENTS  :  $1 - path/to/mountpoint
#===============================================================================
function umount_fs()
{
    if ! umount $1 $2 > /dev/null 2>&1 ; then
        echo "Failed to umount" $1
        exit 127;
    fi
    return 0
}

#===  FUNCTION  ================================================================
#         NAME:  bail_out
#  DESCRIPTION:  if something goes wrong, try hard not to leave stale
#                directories and unused mounts behind.
#===============================================================================
function bail_out()
{
    umount "${TMPMNT}" > /dev/null 2>&1
    rm -fr "${TMPMNT}" > /dev/null 2>&1

    umount "${MNTPOINT}" > /dev/null 2>&1
    rm -fr "${MNTPOINT}" > /dev/null 2>&1

    rm -fr "${ROOTFS_PATH}" > /dev/null 2>&1
}
trap bail_out EXIT

#===  FUNCTION  ================================================================
#         NAME:  main
#  DESCRIPTION:  main entry point
#  ARGUMENTS  :  $1 - path/to/legacy.iso
#  ARGUMENTS  :  $2 - path/to/new.iso
#  ARGUMENTS  :  $3 - CDLABEL (volume name)
#===============================================================================
function main()
{
    LEGACY_ISOPATH=$1
    OUTPUT_ISOPATH=$2
    CDLABEL=$3
    WORKDIR=$(dirname ${OUTPUT_ISOPATH})

    DEBIAN_SYSLINUX_PATH=/usr/lib/ISOLINUX
    REDHAT_SYSLINUX_PATH=/usr/share/syslinux

    if [[ -e ${DEBIAN_SYSLINUX_PATH} ]]; then
        SYSLINUX_PATH=${DEBIAN_SYSLINUX_PATH}
    elif [[ -e ${REDHAT_SYSLINUX_PATH} ]]; then
        SYSLINUX_PATH=${REDHAT_SYSLINUX_PATH}
    else
        echo "Your syslinux/isolinux installation could not be found"
        exit 127;
    fi

    GRUB_MOD_PATH=/usr/lib/grub/x86_64-efi

    if [[ ! -e ${GRUB_MOD_PATH} ]]; then
        echo "Your grub-efi installation could not be found"
        exit 127;
    fi

    # copy rootfs from legacy iso
    MNTPOINT=$(mktmpdir /tmp)
    mount_fs ${LEGACY_ISOPATH} ${MNTPOINT}
    cp_a ${MNTPOINT} ${WORKDIR}
    umount_fs ${MNTPOINT}
    rm -fr ${MNTPOINT} > /dev/null 2>&1

    # generate efiboot partition
    ROOTFS_DIR=$(basename ${MNTPOINT})
    ROOTFS_PATH=${WORKDIR}/${ROOTFS_DIR}
    populate_efiboot_img ${CDLABEL} ${ROOTFS_PATH}/isolinux
    gen_iso_image ${OUTPUT_ISOPATH} ${CDLABEL} ${SYSLINUX_PATH} ${ROOTFS_PATH}
    rm -fr ${ROOTFS_PATH}
}

main ${ARG_INPUT} ${ARG_OUTPUT} ${ARG_CDLABEL}
